### ISSUE TITLE
ArcGIS Enterprise 10.5 Support?

### ISSUE THREAD

**Issue by simongis** [jgrayson-apl/VectorBasemapStyleEditor#5]
I can use your tool fine with our ArcGIS Online account.  However, when trying to update the styles against the same vector basemaps in my Portal for ArcGIS, it has an issue updating the styles. 

_Invalid style file. Uploaded style files must be correctly formatted._

Was wondering if this tool will work against ArcGIS Enterprise?

**Comment by CraigCleveland** [comment]
@jakc I'm not sure this app supports Portal at all "out of the box".  Have you tried the [Vector Tile Style Editor](https://github.com/Esri/arcgis-vectortile-style-editor)?  I was able to get that working against a Portal (10.4.1 and 10.5) with some minor tweaks to the main.js file.  I realize it's not the same thing, but an option nonetheless.

**Comment by jgrayson-apl** [comment]
Correct, this version of the app doesn't support local Portals; it only supports ArcGIS.com.
