### ISSUE TITLE
issue with editing style, unable to add new attributes

### ISSUE THREAD

**Issue by cpgort** [jgrayson-apl/VectorBasemapStyleEditor#7]
When attempting to style json directing (by clicking on 'id' cell), you have the option to insert a new field type. You are able to edit the value side, however you are unable to edit the field side. Field box is unresponsive, unlike the value box. For example, unable to add "text-halo-..." attribute, when it doesn't already exists. You are able to edit values to existing attributes, but I would like to be able to add a halo (or anything else). Thanks.
![json error](https://user-images.githubusercontent.com/11802512/31906772-ccb6a1f8-b7e6-11e7-80b7-90ca1ee57ef7.png)

**Comment by jgrayson-apl** [comment]
Yes, the current behavior is that only values are editable.  We wanted to prevent users inadvertently breaking styles by accidentally changing the name of a property.  We could remove this restriction, but it would also apply to editing the names of existing properties, not just new ones.  We already present enough warnings about using this part of the app, so I don't see an issue making this change.  We should now be able to edit property names.

**Comment by cpgort** [comment]
Makes sense. Thanks for changing it! It'll be great to have more control over editing. And great work on this editor!
